# Generated by Django 3.2 on 2021-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210504_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetest',
            name='cloud_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
