# Generated by Django 3.2 on 2021-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_imagetest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='cloud_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
