# Generated by Django 3.2 on 2021-05-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_imagetest_cloud_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTest',
        ),
    ]
